# Address for the backend hub to listen on for WebSocket connections.
backendListenAddress: ":8443"

# Address for the peer hub to listen on for mTLS-secured connections from other Nexus nodes.
peerListenAddress: ":8444"

# TLS certificate and key for the hub servers.
# These are used for both backend and peer connections. For peers, this certificate
# acts as the node's unique, verifiable identity.
# It MUST be a publicly-trusted certificate (e.g., from Let's Encrypt).
hubTlsCertFile: "/path/to/your/fullchain.pem"
hubTlsKeyFile: "/path/to/your/privkey.pem"

# Ports to listen on for public client traffic.
# Port 80 is treated as L7 HTTP, all others as L4 TCP.
relayPorts:
  - 443
  - 80

# Time in seconds that a client connection can be idle before being closed.
# Set to 0 to disable idle timeouts.
idleTimeoutSeconds: 60

# A secret used to authenticate connections with backends.
# Backends must present a valid JWT signed with this secret.
backendsJWTSecret: "a-very-strong-jwt-secret-for-the-central-authorizer"

# Peer-to-peer mesh configuration.
# A map of other Nexus nodes that this node will connect to.
peers:
  - "wss://nexus-eu.example.com:8444/mesh"
  - "wss://nexus-ap.example.com:8444/mesh"

# Peer authentication settings using mutual TLS (mTLS).
peerAuthentication:
  # An array of domain suffixes. An incoming peer connection will only be
  # accepted if it presents a valid TLS certificate for a domain name
  # ending in one of these suffixes.
  trustedDomainSuffixes:
    - ".proxy.example.com"

